import Head from "next/head";
import Image from "next/image";
import MovilImage from "public/image-product-mobile.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col h-full bg-[#F2EBE3] ">
        <main className="flex flex-col h-full p-5">
          <Image
            src={MovilImage}
            width={686}
            height={480}
            alt="product-image"
            className="rounded-t-2xl"
          ></Image>
          <div className="flex flex-col h-full p-5 justify-between bg-white rounded-b-2xl">
            <p className="capital">perfume</p>
            <p id="h1 font-['Montserrat']" className="text-4xl font-bold">
              Gabrielle Essence Eau De Parfum
            </p>
            <p className="text-[#6C7289]/80">
              A floral, solar and voluptuous interpretation composed by Olivier
              Polge, Perfumer-Creator for the House of CHANEL.
            </p>
            <div className="flex items-center">
              <p className="text-[#3C8067] text-2xl font-bold"> $149.99</p>
              <p className="ml-3 line-through">$169.99</p>
            </div>

            <button className="bg-[#3C8067] p-3 text-white rounded-lg">
              Add to Cart
            </button>
          </div>
        </main>
        <footer className="flex flex-col h-[55px] items-center bg-blue-400">
          <div className="flex">
            <p>Challenge by </p>
            <a
              href="https://www.frontendmentor.io?ref=challenge"
              target="_blank"
            >
              {" "}
              Frontend Mentor
            </a>
          </div>
          <div className="flex">
            <p>Coded by </p>
            <a
              href="https://github.com/ReneOsvaldoCamachoFernandez"
              target="_blank"
            >
              {" "}
              Rene Osvaldo Camacho Fernandez.
            </a>
          </div>
        </footer>
      </div>
    </>
  );
}
